### ISSUE TITLE
Getting exception on nougat and android O

### ISSUE THREAD

**Issue by krunalindrodiya** [Duraiamuthan/VPN-Android#12]
It's working fine in below nougat. But when i am going to connect in nougat and android o, it's having crash on connecting vpn. Below is crash log.
`java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrypto.so" not found
                                                                      at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
                                                                      at java.lang.System.loadLibrary(System.java:1657)
                                                                      at com.openvpn.Durai.core.NativeUtils.<clinit>(NativeUtils.java:12)
                                                                      at com.openvpn.Durai.core.NativeUtils.jniclose(Native Method)
                                                                      at com.openvpn.Durai.core.OpenVpnManagementThread.protectFileDescriptor(OpenVpnManagementThread.java:179)
                                                                      at com.openvpn.Durai.core.OpenVpnManagementThread.processNeedCommand(OpenVpnManagementThread.java:391)
                                                                      at com.openvpn.Durai.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:231)
                                                                      at com.openvpn.Durai.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:202)
                                                                      at com.openvpn.Durai.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:150)
                                                                      at java.lang.Thread.run(Thread.java:764)`

**Comment by sirmordred** [comment]
android is not exporting native libraries anymore (started from O version)
dev is busy probably(or abandoned the project already) ı dunno, but i will fork the project and implement some improvements,fixes soon
:+1:

**Comment by ibrahimnasson** [comment]
@sirmordred please if you are done improving and fixing would you let me know

**Comment by mjavier99** [comment]
Hi, @sirmordred, tellme if you have solved that issue?. Thank you.

**Comment by sirmordred** [comment]
Sorry guys i haven't found time to look, but the issue can be solved by placing libcrypto.so into /system/lib (workaround) i guess
